# site settings
title: Luis Fernandez Jr. | Cybersecurity
subtitle: Cybersecurity
email: jrluisfernandez@gmail.com
avatar: /assets/images/pic01.img
description: I am interactive. It's my intent to find solutions, my perseverance comes from connecting consumers with today's technology. Technology Systems are complex and require understanding. Today's consumers are more connected than ever before, that's why I support and secure their experience. 
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://avatars0.githubusercontent.com/u/40038841?s=460&v=4
facebook_url: https://www.facebook.com/
github_url: https://github.com/LuisFernandezJr
instagram_url: 
linkedin_url: https://www.linkedin.com/in/luisfernandezjr/
pinterest_url:
slack_url:
twitter_url: 
#curious aren't you? :)

#plugins
plugins:
  - jekyll-avatar

# build settings
markdown: kramdown

sass:
  style: compressed
